video_path: 'MiniIPN'
annotation_path: 'MiniIPN/mini_ipn.json'
result_path: 'cnn_lstm\'
save_name: 'cnn_lstm'
sample_size: 112
sample_duration: 32
batch_size: 8
n_epochs: 5
n_threads: 8
model: 'cnn-lstm'
checkpoint: 1