video_path: '../../MiniIPN'
annotation_path: '../../MiniIPN/mini_ipn.json'
result_path: 'nvgesture/'
save_name: 'nvgesture_resnext-101'
sample_size: 112
sample_duration: 16
batch_size: 8
n_epochs: 5
pretrain_path: '../../models/nv_resnext_101_Depth_32.pth'
pretrain_dataset: 'nv'
n_threads: 8
model: 'resnext'
checkpoint: 1