video_path: 'MiniIPN'
annotation_path: 'MiniIPN/mini_ipn.json'
result_path: 'ipn/'
save_name: 'test_model_resnext-101'
sample_size: 112
sample_duration: 32
batch_size: 8
n_epochs: 5
pretrain_path: 'models/ipn_resnext_101.pth'
pretrain_dataset: 'ipn'
n_threads: 8
model: 'resnext'
checkpoint: 1