video_path: 'IPN_hand/dataset/HandGestures/IPN_dataset'
annotation_path: 'IPN_hand/annotation_ipnGesture/mini_ipn.json'
result_path: 'testing/'
save_name: 'test_model_resnext-101'
sample_size: 112
sample_duration: 32
batch_size: 8
n_epochs: 5
pretrain_path: 'dynamic/model/jeseter/jester_resnext-101.pth'
pretrain_dataset: 'jester'
n_threads: 8
model: 'resnext'
checkpoint: 1