video_path: 'D:\Projects\ML\MiniIPN'
annotation_path: 'D:\Projects\ML\MiniIPN\mini_ipn.json'
result_path: 'cnn_lstm\'
save_name: 'cnn_lstm'
sample_size: 112
sample_duration: 32
batch_size: 8
n_epochs: 5
pretrain_path: 'dynamic/model/lstm/cnn_lstm.pth'
n_threads: 8
model: 'cnn-lstm'
checkpoint: 1